# Generated by Django 5.0.7 on 2024-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='poste',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'ADMINISTRATEUR'), ('UTILISATEUR', 'UTILISATEUR'), ('MANAGER', 'MANAGER'), ('SERVEUR', 'SERVEUR')], max_length=50, verbose_name='catégorie utilisateur'),
        ),
    ]
