# Generated by Django 5.0.7 on 2024-07-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTO', '0002_remove_commanditems_name_commanditems_commande_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commanditems',
            old_name='commande_id',
            new_name='command_id',
        ),
    ]
