# Generated by Django 4.2.7 on 2024-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boison', models.CharField(max_length=100, unique=True)),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.FloatField()),
                ('date_stock', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_stock'],
            },
        ),
        migrations.CreateModel(
            name='VenteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('nombre', models.PositiveIntegerField(default=1)),
                ('delete_alt', models.BooleanField(default=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('vente_boison', models.ManyToManyField(to='BAR.stockmodel')),
            ],
            options={
                'ordering': ['-date_vente'],
            },
        ),
    ]
